### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by LazeMSS** [NilsRo/OctoPrint-SlicerEstimator#18]
I get this javascript error:
main.js:475 Error instantiating slicerEstimatorViewModel : TypeError: Cannot read property 'subscribe' of undefined
    at new SlicerEstimatorViewModel (http://192.168.1.29/plugin/SlicerEstimator/static/js/SlicerEstimator.js:48:27)
    at _createViewModelInstance (http://192.168.1.29/static/js/app/main.js:374:16)
    at HTMLDocument.<anonymous> (http://192.168.1.29/static/js/app/main.js:466:37)
    at e (http://192.168.1.29/static/js/lib/jquery/jquery.min.js:2:30005)
    at t (http://192.168.1.29/static/js/lib/jquery/jquery.min.js:2:30307)

Running chrome with: OctoPrint 1.5.3Python 3.7.3OctoPi 0.17.0

**Comment by NilsRo** [comment]
Solved in version 1.0.2
