### ISSUE TITLE
Error in log when another estimator is in use

### ISSUE THREAD

**Issue by ccutrer** [NilsRo/OctoPrint-SlicerEstimator#72]
## Description

I use a different plugin for time estimates, and SlicerEstimator for its metadata parsing. But in this configuration, I get the following error all through the log:

```
2024-03-25 16:43:07,424 - octoprint.util.comm - ERROR - Error while processing hook SlicerEstimator for phase sending and command TIME_LEFT:
Traceback (most recent call last):
  File "/home/cody/oprint/lib/python3.9/site-packages/octoprint/util/comm.py", line 4872, in _process_atcommand_phase
    hook(self, phase, atcommand, parameters, tags=tags)
  File "/home/cody/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/cody/oprint/lib/python3.9/site-packages/octoprint_SlicerEstimator/__init__.py", line 163, in on_at_command
    self._estimator.time_left = float(parameters)
AttributeError: 'NoneType' object has no attribute 'time_left'
```

**Plugins installed**
- BGCode[bgcode] v0.2.0
- Camera Streamer Control[camerastreamer_control] v1.0.1
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.28.0
- Octolapse[octolapse] v0.4.5
- OctoPod Plugin[octopod] v0.3.16
- Octoprint Display ETA[display_eta] v2.2.0
- Prusa Mini ETA Plugin[prusa_mini_eta] v0.1.4
- Slicer Estimator[SlicerEstimator] v1.6.4
- Slicer Thumbnails[prusaslicerthumbnails] v1.0.7

**Settings**
- average_prio: false
- metadata_filelist: true
- metadata_filelist_align: top
- metadata_list: 
- metadata_printer: true
- metadata_slicer: true
Installed plugins: (SlicerEstimator)
- useDevChannel: false
- use_assets: true

**Software versions**
- OctoPrint 1.9.3
- Python 3.9.2
- OctoPi* 1.0.0cam (build 2023.10.09.154319)

**Comment by NilsRo** [comment]
If you switch an the dev branch in the last tab of the plugin the type if the estimator is is checked. Please try if the error is gone then. For your case I perhaps have to add a setting to disable the estimator in the future.
